# logtype can take: debug, info, notice, warning, error, critical
# notice is the default
logtype = "notice"

[default]
mp4folderpath = ""
# time to sleep in minute(s)
sleeptime = 4

[email]
from = ""
smtp = ""
port = ""
login = ""
password = ""
sendTo = [""]
