# logtype can take: debug, info, notice, warning, error, critical
# notice is the default
logtype = "notice"

[default]
mp4folderpath = "/tmp"
# time to sleep in seconde(s)
sleeptime = 30

[email]
from = ""
smtp = ""
port = ""
login = ""
password = ""
sendTo = [""]
